# Generated by Django 4.2.1 on 2023-05-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='context',
            field=models.TextField(default='test1'),
            preserve_default=False,
        ),
    ]
